// Don't edit this file. It is automatically generated by make_flash_map.py.

{479106, 79, 70}, // ICON_SUN
{490166, 79, 70}, // ICON_TYPE2
{501226, 79, 70}, // ICON_MONEY
{512286, 79, 70}, // ICON_LOCK_OPEN
{523346, 79, 70}, // ICON_COG
{534406, 30, 30}, // STATUS_ICON_WIFI
{536206, 30, 30} // STATUS_ICON_ETHERNET
