// Don't edit this file. It is automatically generated by make_flash_map.py.

{43520, 79, 70}, // ICON_SUN
{54580, 79, 70}, // ICON_TYPE2
{65640, 79, 70}, // ICON_MONEY
{76700, 79, 70}, // ICON_LOCK_OPEN
{87760, 79, 70}, // ICON_COG
{98820, 30, 30}, // STATUS_ICON_WIFI
{100620, 30, 30} // STATUS_ICON_ETHERNET
