// Don't edit this file. It is automatically generated by make_flash_map.py.

{469932, 79, 70}, // ICON_SUN
{480992, 79, 70}, // ICON_TYPE2
{492052, 79, 70}, // ICON_MONEY
{503112, 79, 70}, // ICON_LOCK_OPEN
{514172, 79, 70}, // ICON_COG
{525232, 30, 30}, // STATUS_ICON_WIFI
{527032, 30, 30} // STATUS_ICON_ETHERNET
