// Don't edit this file. It is automatically generated by make_flash_map.py.

#define SPRITE_ICON_SUN 0
#define SPRITE_ICON_TYPE2 1
#define SPRITE_ICON_MONEY 2
#define SPRITE_ICON_LOCK_OPEN 3
#define SPRITE_ICON_COG 4
#define SPRITE_STATUS_ICON_WIFI 5
#define SPRITE_STATUS_ICON_ETHERNET 6
